PYTTSX3_VOICES = {
    # created via:
    # engine = pyttsx3.init()
    # voices = engine.getProperty('voices')
    # print({v.name: v.id for v in voices})
    'Albert': 'com.apple.speech.synthesis.voice.Albert',
    'Alice': 'com.apple.voice.compact.it-IT.Alice',
    'Alva': 'com.apple.voice.compact.sv-SE.Alva',
    'Amélie': 'com.apple.voice.compact.fr-CA.Amelie',
    'Amira': 'com.apple.voice.compact.ms-MY.Amira',
    'Anna': 'com.apple.voice.compact.de-DE.Anna',
    'Bad News': 'com.apple.speech.synthesis.voice.BadNews',
    'Bahh': 'com.apple.speech.synthesis.voice.Bahh',
    'Bells': 'com.apple.speech.synthesis.voice.Bells',
    'Boing': 'com.apple.speech.synthesis.voice.Boing',
    'Bubbles': 'com.apple.speech.synthesis.voice.Bubbles',
    'Carmit': 'com.apple.voice.compact.he-IL.Carmit',
    'Cellos': 'com.apple.speech.synthesis.voice.Cellos',
    'Damayanti': 'com.apple.voice.compact.id-ID.Damayanti',
    'Daniel': 'com.apple.voice.compact.en-GB.Daniel',
    'Daria': 'com.apple.voice.compact.bg-BG.Daria',
    'Wobble': 'com.apple.speech.synthesis.voice.Deranged',
    'Eddy (German (Germany))': 'com.apple.eloquence.de-DE.Eddy',
    'Eddy (English (UK))': 'com.apple.eloquence.en-GB.Eddy',
    'Eddy (English (US))': 'com.apple.eloquence.en-US.Eddy',
    'Eddy (Spanish (Spain))': 'com.apple.eloquence.es-ES.Eddy',
    'Eddy (Spanish (Mexico))': 'com.apple.eloquence.es-MX.Eddy',
    'Eddy (Finnish (Finland))': 'com.apple.eloquence.fi-FI.Eddy',
    'Eddy (French (Canada))': 'com.apple.eloquence.fr-CA.Eddy',
    'Eddy (French (France))': 'com.apple.eloquence.fr-FR.Eddy',
    'Eddy (Italian (Italy))': 'com.apple.eloquence.it-IT.Eddy',
    'Eddy (Portuguese (Brazil))': 'com.apple.eloquence.pt-BR.Eddy',
    'Ellen': 'com.apple.voice.compact.nl-BE.Ellen',
    'Flo (German (Germany))': 'com.apple.eloquence.de-DE.Flo',
    'Flo (English (UK))': 'com.apple.eloquence.en-GB.Flo',
    'Flo (English (US))': 'com.apple.eloquence.en-US.Flo',
    'Flo (Spanish (Spain))': 'com.apple.eloquence.es-ES.Flo',
    'Flo (Spanish (Mexico))': 'com.apple.eloquence.es-MX.Flo',
    'Flo (Finnish (Finland))': 'com.apple.eloquence.fi-FI.Flo',
    'Flo (French (Canada))': 'com.apple.eloquence.fr-CA.Flo',
    'Flo (French (France))': 'com.apple.eloquence.fr-FR.Flo',
    'Flo (Italian (Italy))': 'com.apple.eloquence.it-IT.Flo',
    'Flo (Portuguese (Brazil))': 'com.apple.eloquence.pt-BR.Flo',
    'Fred': 'com.apple.speech.synthesis.voice.Fred',
    'Good News': 'com.apple.speech.synthesis.voice.GoodNews',
    'Grandma (German (Germany))': 'com.apple.eloquence.de-DE.Grandma',
    'Grandma (English (UK))': 'com.apple.eloquence.en-GB.Grandma',
    'Grandma (English (US))': 'com.apple.eloquence.en-US.Grandma',
    'Grandma (Spanish (Spain))': 'com.apple.eloquence.es-ES.Grandma',
    'Grandma (Spanish (Mexico))': 'com.apple.eloquence.es-MX.Grandma',
    'Grandma (Finnish (Finland))': 'com.apple.eloquence.fi-FI.Grandma',
    'Grandma (French (Canada))': 'com.apple.eloquence.fr-CA.Grandma',
    'Grandma (French (France))': 'com.apple.eloquence.fr-FR.Grandma',
    'Grandma (Italian (Italy))': 'com.apple.eloquence.it-IT.Grandma',
    'Grandma (Portuguese (Brazil))': 'com.apple.eloquence.pt-BR.Grandma',
    'Grandpa (German (Germany))': 'com.apple.eloquence.de-DE.Grandpa',
    'Grandpa (English (UK))': 'com.apple.eloquence.en-GB.Grandpa',
    'Grandpa (English (US))': 'com.apple.eloquence.en-US.Grandpa',
    'Grandpa (Spanish (Spain))': 'com.apple.eloquence.es-ES.Grandpa',
    'Grandpa (Spanish (Mexico))': 'com.apple.eloquence.es-MX.Grandpa',
    'Grandpa (Finnish (Finland))': 'com.apple.eloquence.fi-FI.Grandpa',
    'Grandpa (French (Canada))': 'com.apple.eloquence.fr-CA.Grandpa',
    'Grandpa (French (France))': 'com.apple.eloquence.fr-FR.Grandpa',
    'Grandpa (Italian (Italy))': 'com.apple.eloquence.it-IT.Grandpa',
    'Grandpa (Portuguese (Brazil))': 'com.apple.eloquence.pt-BR.Grandpa',
    'Jester': 'com.apple.speech.synthesis.voice.Hysterical',
    'Ioana': 'com.apple.voice.compact.ro-RO.Ioana',
    'Jacques': 'com.apple.eloquence.fr-FR.Jacques',
    'Joana': 'com.apple.voice.compact.pt-PT.Joana',
    'Junior': 'com.apple.speech.synthesis.voice.Junior',
    'Kanya': 'com.apple.voice.compact.th-TH.Kanya',
    'Karen': 'com.apple.voice.compact.en-AU.Karen',
    'Kathy': 'com.apple.speech.synthesis.voice.Kathy',
    'Kyoko': 'com.apple.voice.compact.ja-JP.Kyoko',
    'Lana': 'com.apple.voice.compact.hr-HR.Lana',
    'Laura': 'com.apple.voice.compact.sk-SK.Laura',
    'Lekha': 'com.apple.voice.compact.hi-IN.Lekha',
    'Lesya': 'com.apple.voice.compact.uk-UA.Lesya',
    'Linh': 'com.apple.voice.compact.vi-VN.Linh',
    'Luciana': 'com.apple.voice.compact.pt-BR.Luciana',
    'Majed': 'com.apple.voice.compact.ar-001.Maged',
    'Tünde': 'com.apple.voice.compact.hu-HU.Mariska',
    'Meijia': 'com.apple.voice.compact.zh-TW.Meijia',
    'Melina': 'com.apple.voice.compact.el-GR.Melina',
    'Milena': 'com.apple.voice.compact.ru-RU.Milena',
    'Moira': 'com.apple.voice.compact.en-IE.Moira',
    'Mónica': 'com.apple.voice.compact.es-ES.Monica',
    'Montse': 'com.apple.voice.compact.ca-ES.Montserrat',
    'Nora': 'com.apple.voice.compact.nb-NO.Nora',
    'Organ': 'com.apple.speech.synthesis.voice.Organ',
    'Paulina': 'com.apple.voice.compact.es-MX.Paulina',
    'Superstar': 'com.apple.speech.synthesis.voice.Princess',
    'Ralph': 'com.apple.speech.synthesis.voice.Ralph',
    'Reed (German (Germany))': 'com.apple.eloquence.de-DE.Reed',
    'Reed (English (UK))': 'com.apple.eloquence.en-GB.Reed',
    'Reed (English (US))': 'com.apple.eloquence.en-US.Reed',
    'Reed (Spanish (Spain))': 'com.apple.eloquence.es-ES.Reed',
    'Reed (Spanish (Mexico))': 'com.apple.eloquence.es-MX.Reed',
    'Reed (Finnish (Finland))': 'com.apple.eloquence.fi-FI.Reed',
    'Reed (French (Canada))': 'com.apple.eloquence.fr-CA.Reed',
    'Reed (Italian (Italy))': 'com.apple.eloquence.it-IT.Reed',
    'Reed (Portuguese (Brazil))': 'com.apple.eloquence.pt-BR.Reed',
    'Rishi': 'com.apple.voice.compact.en-IN.Rishi',
    'Rocko (German (Germany))': 'com.apple.eloquence.de-DE.Rocko',
    'Rocko (English (UK))': 'com.apple.eloquence.en-GB.Rocko',
    'Rocko (English (US))': 'com.apple.eloquence.en-US.Rocko',
    'Rocko (Spanish (Spain))': 'com.apple.eloquence.es-ES.Rocko',
    'Rocko (Spanish (Mexico))': 'com.apple.eloquence.es-MX.Rocko',
    'Rocko (Finnish (Finland))': 'com.apple.eloquence.fi-FI.Rocko',
    'Rocko (French (Canada))': 'com.apple.eloquence.fr-CA.Rocko',
    'Rocko (French (France))': 'com.apple.eloquence.fr-FR.Rocko',
    'Rocko (Italian (Italy))': 'com.apple.eloquence.it-IT.Rocko',
    'Rocko (Portuguese (Brazil))': 'com.apple.eloquence.pt-BR.Rocko',
    'Samantha': 'com.apple.voice.compact.en-US.Samantha',
    'Sandy (German (Germany))': 'com.apple.eloquence.de-DE.Sandy',
    'Sandy (English (UK))': 'com.apple.eloquence.en-GB.Sandy',
    'Sandy (English (US))': 'com.apple.eloquence.en-US.Sandy',
    'Sandy (Spanish (Spain))': 'com.apple.eloquence.es-ES.Sandy',
    'Sandy (Spanish (Mexico))': 'com.apple.eloquence.es-MX.Sandy',
    'Sandy (Finnish (Finland))': 'com.apple.eloquence.fi-FI.Sandy',
    'Sandy (French (Canada))': 'com.apple.eloquence.fr-CA.Sandy',
    'Sandy (French (France))': 'com.apple.eloquence.fr-FR.Sandy',
    'Sandy (Italian (Italy))': 'com.apple.eloquence.it-IT.Sandy',
    'Sandy (Portuguese (Brazil))': 'com.apple.eloquence.pt-BR.Sandy',
    'Sara': 'com.apple.voice.compact.da-DK.Sara',
    'Satu': 'com.apple.voice.compact.fi-FI.Satu',
    'Shelley (German (Germany))': 'com.apple.eloquence.de-DE.Shelley',
    'Shelley (English (UK))': 'com.apple.eloquence.en-GB.Shelley',
    'Shelley (English (US))': 'com.apple.eloquence.en-US.Shelley',
    'Shelley (Spanish (Spain))': 'com.apple.eloquence.es-ES.Shelley',
    'Shelley (Spanish (Mexico))': 'com.apple.eloquence.es-MX.Shelley',
    'Shelley (Finnish (Finland))': 'com.apple.eloquence.fi-FI.Shelley',
    'Shelley (French (Canada))': 'com.apple.eloquence.fr-CA.Shelley',
    'Shelley (French (France))': 'com.apple.eloquence.fr-FR.Shelley',
    'Shelley (Italian (Italy))': 'com.apple.eloquence.it-IT.Shelley',
    'Shelley (Portuguese (Brazil))': 'com.apple.eloquence.pt-BR.Shelley',
    'Sinji': 'com.apple.voice.compact.zh-HK.Sinji',
    'Tessa': 'com.apple.voice.compact.en-ZA.Tessa',
    'Thomas': 'com.apple.voice.compact.fr-FR.Thomas',
    'Tingting': 'com.apple.voice.compact.zh-CN.Tingting',
    'Trinoids': 'com.apple.speech.synthesis.voice.Trinoids',
    'Whisper': 'com.apple.speech.synthesis.voice.Whisper',
    'Xander': 'com.apple.voice.compact.nl-NL.Xander',
    'Yelda': 'com.apple.voice.compact.tr-TR.Yelda',
    'Yuna': 'com.apple.voice.compact.ko-KR.Yuna',
    'Zarvox': 'com.apple.speech.synthesis.voice.Zarvox',
    'Zosia': 'com.apple.voice.compact.pl-PL.Zosia',
    'Zuzana': 'com.apple.voice.compact.cs-CZ.Zuzana'}